# Generated by Django 5.1.5 on 2025-02-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_group_student_group_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Class',
        ),
    ]
