# Generated by Django 5.1.5 on 2025-02-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_group_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
