
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz_app_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network


networks:
  app_network:

volumes:
  postgres_data: