# Generated by Django 5.1.5 on 2025-02-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='duration',
        ),
    ]
