# Generated by Django 5.1.5 on 2025-02-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='group',
            new_name='groups',
        ),
    ]
